resourcePath=res
logPath = logs
modsPath=${resourcePath}/mods
FxmlPath=${resourcePath}/layouts
stylesheetPath = ${resourcePath}/styles
visualPath = ${resourcePath}/visual
guiPath = ${visualPath}/gui
svgsPath=res/visual/gui/svgs
svgsButtonsPath=res/visual/gui/svgs/buttons
visualGuiIconsPath = ${guiPath}/icons
visualFontPath = ${visualPath}/fonts
visualGuiNewPath = ${guiPath}/new

logErr = ${logPath}/errors
logOut = ${logPath}/output

FXMLDownloadInetPath = ${FxmlPath}/DownloadInet.fxml
FXMLAudioHostPath=${FxmlPath}/host/AudioHost.fxml
FXMLTagEditorPath=${FxmlPath}/TagEditor.fxml
FXMLSettingsPath=${FxmlPath}/Settings.fxml
FXMLMetaDataPath=${FxmlPath}/Metadata.fxml
FXMLTrackStatisticsPath=${FxmlPath}/TrackStatistics.fxml
FXMLTracksStatisticsPath=${FxmlPath}/TracksStatistics.fxml

contextMenuStyles = ${stylesheetPath}/pantyhose/context-menu-style.css
listview = ${stylesheetPath}/listview.css
scrollbar-fixed-width = ${stylesheetPath}/scrollbar-fixed-width.css
slider-custom = ${stylesheetPath}/slider-custom.css
root = ${stylesheetPath}/root.css
vsthost = ${stylesheetPath}/vsthost.css
tabpane = ${stylesheetPath}/tabpane.css
scrollpane-scroll-bar = ${stylesheetPath}/scrollpane-scroll-bar.css

album_art_logo = ${guiPath}/logo.png
logoHd = ${guiPath}/logo-hd.png

playlistIcon = ${visualGuiIconsPath}/playlist.jpg

playButton=${svgsButtonsPath}/play.svg
prevButton=${svgsButtonsPath}/prev.svg
nextButton=${svgsButtonsPath}/next.svg
pauseButton=${svgsButtonsPath}/pause.svg
nextPlaylistButton=${svgsButtonsPath}/next_playlist.svg
playlistButton=${svgsButtonsPath}/playlist.svg
prevPlaylistButton=${svgsButtonsPath}/prev_playlist.svg
removePlaylistFromDiskButton=${svgsButtonsPath}/playlist_delete_from_disk.svg
removePlaylistFromAppButton=${svgsButtonsPath}/playlist_delete_from_app.svg

hideLeftButton=${svgsButtonsPath}/hide_left.svg
hideRightButton=${svgsButtonsPath}/hide_right.svg
commons=${svgsButtonsPath}/commons.svg

lightaudio = ${visualGuiIconsPath}/lightaudio.png
hitmos = ${visualGuiIconsPath}/hitmos.png
musmore = ${visualGuiIconsPath}/musmore.png
lastfm = ${visualGuiIconsPath}/lastfm.png
spotify = ${visualGuiIconsPath}/spotify.png
sound_cloud = ${visualGuiIconsPath}/sound_cloud.png
apple = ${visualGuiIconsPath}/apple.png

font = ${visualFontPath}/main_fonta.ttf
main_font = ${visualFontPath}/Comfortaa/Comfortaa-VariableFont_wght.ttf

audio=${resourcePath}/audio
audio_intro=${audio}/intro_cassette.wav

splashesMessages = ${resourcePath}/splashes.json

lang = ${resourcePath}/lang/json
pluginsPath = ${audio}/plugins